# Generated by Django 5.2.14 on 2026-05-27 08:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boundary_cases', '0001_initial'),
        ('orders', '0002_orderchangerequest'),
        ('organization', '0001_initial'),
        ('planning', '0002_plannedworkitem_color_code_and_more'),
        ('production_release', '0001_initial'),
        ('style_technical', '0003_style_approved_wash_standard_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineRealignmentRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('request_no', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=24)),
                ('fit_status', models.CharField(choices=[('FIT', 'Fit'), ('ACCEPTABLE_WITH_REALIGNMENT', 'Acceptable with realignment'), ('BLOCKED', 'Blocked')], default='ACCEPTABLE_WITH_REALIGNMENT', max_length=40)),
                ('target_output', models.PositiveIntegerField()),
                ('expected_output_before', models.PositiveIntegerField(default=0)),
                ('expected_output_after', models.PositiveIntegerField(default=0)),
                ('changeover_minutes', models.PositiveIntegerField(default=0)),
                ('approval_required', models.BooleanField(default=True)),
                ('risk_status', models.CharField(choices=[('ON_TRACK', 'On track'), ('WATCH', 'Watch'), ('ACTION', 'Action required'), ('CRITICAL', 'Critical')], default='WATCH', max_length=20)),
                ('recommendations_json', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_line_realignments', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_line_realignments', to=settings.AUTH_USER_MODEL)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_realignment_requests', to='style_technical.operationbulletin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realignment_requests', to='organization.line')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_realignment_requests', to='orders.productionorder')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_line_realignments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'request_no'],
            },
        ),
        migrations.CreateModel(
            name='LineRealignmentGap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('gap_type', models.CharField(choices=[('MACHINE', 'Machine'), ('SKILL', 'Skill'), ('BOTTLENECK', 'Bottleneck')], max_length=24)),
                ('label', models.CharField(max_length=160)),
                ('required', models.PositiveIntegerField(default=0)),
                ('available', models.PositiveIntegerField(default=0)),
                ('gap', models.IntegerField(default=0)),
                ('recommendation', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('realignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='sewing.linerealignmentrequest')),
            ],
            options={
                'ordering': ['gap_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SewingLineLoading',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('loading_no', models.CharField(max_length=120, unique=True)),
                ('planned_quantity', models.PositiveIntegerField()),
                ('target_output_per_day', models.PositiveIntegerField(default=0)),
                ('target_efficiency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('expected_defect_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('planning_zone', models.CharField(default='FLEXIBLE_ZONE', max_length=32)),
                ('planned_shift', models.CharField(default='DAY', max_length=40)),
                ('color_code', models.CharField(blank=True, max_length=80)),
                ('shade_lot', models.CharField(blank=True, max_length=80)),
                ('fit_status', models.CharField(choices=[('FIT', 'Fit'), ('ACCEPTABLE_WITH_REALIGNMENT', 'Acceptable with realignment'), ('BLOCKED', 'Blocked')], default='FIT', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('risk_status', models.CharField(choices=[('ON_TRACK', 'On track'), ('WATCH', 'Watch'), ('ACTION', 'Action required'), ('CRITICAL', 'Critical')], default='ON_TRACK', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_exception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_line_loadings', to='boundary_cases.boundarycaseevent')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing_line_loadings', to='style_technical.operationbulletin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing_line_loadings', to='organization.line')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing_line_loadings', to='orders.productionorder')),
                ('planned_work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sewing_line_loadings', to='planning.plannedworkitem')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing_line_loadings', to='production_release.productionrelease')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workcenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing_line_loadings', to='organization.workcenter')),
            ],
            options={
                'ordering': ['-created_at', 'loading_no'],
            },
        ),
        migrations.CreateModel(
            name='SewingLineAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('operator_count', models.PositiveIntegerField(default=0)),
                ('machine_count', models.PositiveIntegerField(default=0)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing_assignments', to='organization.line')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('line_loading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sewing.sewinglineloading')),
            ],
            options={
                'ordering': ['line__code', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='linerealignmentrequest',
            name='line_loading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realignment_requests', to='sewing.sewinglineloading'),
        ),
        migrations.CreateModel(
            name='SewingOutputEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('client_event_id', models.CharField(max_length=120, unique=True)),
                ('entry_time', models.DateTimeField()),
                ('time_slot', models.CharField(max_length=40)),
                ('gross_qty', models.PositiveIntegerField()),
                ('defect_qty', models.PositiveIntegerField(default=0)),
                ('rework_qty', models.PositiveIntegerField(default=0)),
                ('net_good_qty', models.PositiveIntegerField()),
                ('source', models.CharField(default='DESKTOP', max_length=32)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing_output_entries', to='organization.line')),
                ('line_loading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_entries', to='sewing.sewinglineloading')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing_output_entries', to='orders.productionorder')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sewing_output_entries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SewingOutputCorrection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField()),
                ('old_value_json', models.JSONField(blank=True, default=dict)),
                ('new_value_json', models.JSONField(blank=True, default=dict)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sewing_output_corrections', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('output_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='sewing.sewingoutputentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sewinglineloading',
            constraint=models.UniqueConstraint(fields=('release', 'line'), name='unique_release_line_loading'),
        ),
        migrations.AddIndex(
            model_name='sewingoutputentry',
            index=models.Index(fields=['order', 'line', 'time_slot'], name='sewing_sewi_order_i_e29e49_idx'),
        ),
    ]
