export const queryKeys = {
  currentUser: ["current-user"] as const,
  factories: ["organization", "factories"] as const,
  departments: ["organization", "departments"] as const,
  workcenters: ["organization", "workcenters"] as const,
  lines: ["organization", "lines"] as const,
  customers: ["master", "customers"] as const,
  buyers: ["master", "buyers"] as const,
  vendors: ["master", "vendors"] as const,
  materials: ["master", "materials"] as const,
  productTypes: ["master", "product-types"] as const,
  machineTypes: ["master", "machine-types"] as const,
  machines: ["master", "machines"] as const,
  thresholds: ["master", "thresholds"] as const,
  styles: ["technical", "styles"] as const,
  boms: ["technical", "boms"] as const,
  operationMasters: ["technical", "operation-masters"] as const,
  operationBulletins: ["technical", "operation-bulletins"] as const,
  washRoutes: ["technical", "wash-routes"] as const,
  lineCapability: ["technical", "line-capability"] as const,
  capacityDays: ["technical", "capacity-days"] as const,
};
