# Generated by Django 5.2.14 on 2026-05-26 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('organization', '0001_initial'),
        ('style_technical', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order_no', models.CharField(max_length=120, unique=True)),
                ('po_number', models.CharField(blank=True, max_length=120)),
                ('order_qty', models.PositiveIntegerField()),
                ('planned_ship_date', models.DateField(blank=True, null=True)),
                ('committed_ship_date', models.DateField()),
                ('planned_pcd_date', models.DateField()),
                ('current_stage', models.CharField(choices=[('CREATED', 'Created'), ('PRE_PRODUCTION', 'Pre-production'), ('PCD_PENDING', 'PCD pending'), ('PCD_READY', 'PCD ready'), ('CUTTING', 'Cutting'), ('SEWING', 'Sewing'), ('WASHING', 'Washing'), ('FINISHING', 'Finishing'), ('PACKING', 'Packing'), ('SHIPMENT_READY', 'Shipment ready'), ('SHIPPED', 'Shipped'), ('ON_HOLD', 'On hold'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=40)),
                ('lifecycle_status', models.CharField(choices=[('CREATED', 'Created'), ('PRE_PRODUCTION', 'Pre-production'), ('PCD_PENDING', 'PCD pending'), ('PCD_READY', 'PCD ready'), ('CUTTING', 'Cutting'), ('SEWING', 'Sewing'), ('WASHING', 'Washing'), ('FINISHING', 'Finishing'), ('PACKING', 'Packing'), ('SHIPMENT_READY', 'Shipment ready'), ('SHIPPED', 'Shipped'), ('ON_HOLD', 'On hold'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=40)),
                ('risk_status', models.CharField(choices=[('ON_TRACK', 'On track'), ('WATCH', 'Watch'), ('ACTION', 'Action required'), ('CRITICAL', 'Critical')], default='ON_TRACK', max_length=20)),
                ('order_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On hold'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='master_data.buyer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='master_data.customer')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='organization.factory')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_orders', to=settings.AUTH_USER_MODEL)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='master_data.producttype')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='style_technical.style')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['committed_ship_date', 'order_no'],
            },
        ),
        migrations.CreateModel(
            name='OrderLifecycleEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('event_code', models.CharField(max_length=100)),
                ('from_stage', models.CharField(blank=True, max_length=40)),
                ('to_stage', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lifecycle_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='orders.productionorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderMilestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('milestone_type', models.CharField(max_length=80)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('DELAYED', 'Delayed'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('delay_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_milestones', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='orders.productionorder')),
            ],
            options={
                'ordering': ['order__order_no', 'planned_date', 'milestone_type'],
                'constraints': [models.UniqueConstraint(fields=('order', 'milestone_type'), name='unique_order_milestone_type')],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.productionorder')),
            ],
            options={
                'ordering': ['order__order_no', 'color', 'size'],
                'constraints': [models.UniqueConstraint(fields=('order', 'size', 'color'), name='unique_order_line_size_color')],
            },
        ),
    ]
