# Generated by Django 5.2.14 on 2026-05-27 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChangeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('request_no', models.CharField(max_length=120, unique=True)),
                ('change_type', models.CharField(choices=[('QUANTITY_CHANGE', 'Quantity change'), ('DELIVERY_DATE_CHANGE', 'Delivery date change'), ('CANCELLATION', 'Cancellation'), ('SHIPMENT_PULL_IN', 'Shipment pull-in')], max_length=32)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=24)),
                ('old_value_json', models.JSONField(blank=True, default=dict)),
                ('new_value_json', models.JSONField(blank=True, default=dict)),
                ('impact_preview', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField()),
                ('disposition_required', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_order_changes', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_order_changes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='orders.productionorder')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_order_changes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'request_no'],
            },
        ),
    ]
