# Generated by Django 5.2.14 on 2026-05-26 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('organization', '0001_initial'),
        ('style_technical', '0001_initial'),
        ('workcenters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationbulletinline',
            name='machine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_lines', to='workcenters.machinetype'),
        ),
        migrations.AddField(
            model_name='operationbulletinline',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='style_technical.operationbulletinline'),
        ),
        migrations.AddField(
            model_name='operationbulletinline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationmaster',
            name='default_machine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_operations', to='workcenters.machinetype'),
        ),
        migrations.AddField(
            model_name='operationmaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationbulletinline',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_lines', to='style_technical.operationmaster'),
        ),
        migrations.AddField(
            model_name='style',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='master_data.buyer'),
        ),
        migrations.AddField(
            model_name='style',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='style',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='master_data.customer'),
        ),
        migrations.AddField(
            model_name='style',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='master_data.producttype'),
        ),
        migrations.AddField(
            model_name='style',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationbulletin',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_bulletins', to='style_technical.style'),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='style_technical.style'),
        ),
        migrations.AddField(
            model_name='stylecomplexity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stylecomplexity',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='washroute',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wash_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='washroute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='washroute',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wash_routes', to='master_data.producttype'),
        ),
        migrations.AddField(
            model_name='washroute',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='style',
            name='default_wash_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_styles', to='style_technical.washroute'),
        ),
        migrations.AddField(
            model_name='washroutestep',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='washroutestep',
            name='machine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wash_route_steps', to='workcenters.machinetype'),
        ),
        migrations.AddField(
            model_name='washroutestep',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='style_technical.washroute'),
        ),
        migrations.AddField(
            model_name='washroutestep',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='washroutestep',
            name='workcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wash_route_steps', to='organization.workcenter'),
        ),
        migrations.AddConstraint(
            model_name='bomline',
            constraint=models.UniqueConstraint(fields=('bom', 'material'), name='unique_bom_line_material'),
        ),
        migrations.AddConstraint(
            model_name='operationbulletinline',
            constraint=models.UniqueConstraint(fields=('bulletin', 'sequence_no'), name='unique_bulletin_sequence'),
        ),
        migrations.AddConstraint(
            model_name='operationbulletin',
            constraint=models.UniqueConstraint(fields=('style', 'version'), name='unique_operation_bulletin_style_version'),
        ),
        migrations.AddConstraint(
            model_name='bomheader',
            constraint=models.UniqueConstraint(fields=('style', 'version'), name='unique_bom_style_version'),
        ),
        migrations.AddConstraint(
            model_name='washroutestep',
            constraint=models.UniqueConstraint(fields=('route', 'sequence_no'), name='unique_wash_route_step_sequence'),
        ),
    ]
