# Generated by Django 5.2.14 on 2026-05-27 07:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_technical', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='approved_wash_standard_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='style',
            name='customer_effect_approval_status',
            field=models.CharField(default='PENDING', max_length=32),
        ),
        migrations.AddField(
            model_name='style',
            name='dry_process_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='style',
            name='fashion_effect_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='style',
            name='max_repeat_cycles',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='style',
            name='post_wash_qc_criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='style',
            name='repeat_cycle_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='style',
            name='repeat_cycle_probability',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='style',
            name='shade_effect_tolerance',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='style',
            name='wash_complexity_class',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='style',
            name='wet_process_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='washroute',
            name='approved_wash_standard_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='washroute',
            name='customer_effect_approval_status',
            field=models.CharField(default='PENDING', max_length=32),
        ),
        migrations.AddField(
            model_name='washroute',
            name='dry_process_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='washroute',
            name='fashion_effect_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='washroute',
            name='max_repeat_cycles',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='washroute',
            name='post_wash_qc_criteria',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='washroute',
            name='repeat_cycle_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='washroute',
            name='repeat_cycle_probability',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='washroute',
            name='shade_effect_tolerance',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='washroute',
            name='wash_complexity_class',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='washroute',
            name='wet_process_required',
            field=models.BooleanField(default=True),
        ),
    ]
