# Generated by Django 5.2.14 on 2026-05-27 04:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('organization', '0001_initial'),
        ('planning', '0001_initial'),
        ('workcenters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('adjustment_date', models.DateField()),
                ('adjustment_type', models.CharField(choices=[('OVERTIME', 'Overtime'), ('DOWNTIME', 'Downtime'), ('MANPOWER', 'Manpower'), ('MAINTENANCE', 'Maintenance')], max_length=24)),
                ('minutes_delta', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='APPROVED', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_capacity_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workcenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacity_adjustments', to='organization.workcenter')),
            ],
            options={
                'ordering': ['workcenter__code', 'adjustment_date', 'adjustment_type'],
            },
        ),
        migrations.CreateModel(
            name='WorkcenterLoadSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('snapshot_date', models.DateField()),
                ('available_minutes', models.PositiveIntegerField(default=0)),
                ('planned_load_minutes', models.PositiveIntegerField(default=0)),
                ('actual_load_minutes', models.PositiveIntegerField(default=0)),
                ('utilization_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('queue_quantity', models.PositiveIntegerField(default=0)),
                ('oldest_queue_age_hours', models.PositiveIntegerField(default=0)),
                ('constraint_status', models.CharField(choices=[('NORMAL', 'Normal'), ('WATCH', 'Watch'), ('OVERLOADED', 'Overloaded'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('risk_status', models.CharField(choices=[('ON_TRACK', 'On track'), ('WATCH', 'Watch'), ('ACTION', 'Action required'), ('CRITICAL', 'Critical')], default='ON_TRACK', max_length=20)),
                ('suggested_action', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('horizon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcenter_load_snapshots', to='planning.planninghorizon')),
                ('top_affected_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_constraint_snapshots', to='orders.productionorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workcenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='load_snapshots', to='organization.workcenter')),
            ],
            options={
                'ordering': ['-utilization_percent', 'workcenter__code'],
                'constraints': [models.UniqueConstraint(fields=('workcenter', 'snapshot_date'), name='unique_workcenter_load_snapshot_day')],
            },
        ),
        migrations.CreateModel(
            name='WorkcenterQueueSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('snapshot_date', models.DateField()),
                ('queue_stage', models.CharField(default='PLANNED', max_length=80)),
                ('queue_quantity', models.PositiveIntegerField(default=0)),
                ('age_hours', models.PositiveIntegerField(default=0)),
                ('risk_status', models.CharField(choices=[('ON_TRACK', 'On track'), ('WATCH', 'Watch'), ('ACTION', 'Action required'), ('CRITICAL', 'Critical')], default='ON_TRACK', max_length=20)),
                ('owner_label', models.CharField(blank=True, max_length=120)),
                ('next_action', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workcenter_queue_snapshots', to='orders.productionorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workcenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_snapshots', to='organization.workcenter')),
            ],
            options={
                'ordering': ['-age_hours', 'order__order_no'],
                'constraints': [models.UniqueConstraint(fields=('workcenter', 'snapshot_date', 'order', 'queue_stage'), name='unique_workcenter_queue_order_stage')],
            },
        ),
    ]
