# Generated by Django 5.2.14 on 2026-05-27 07:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workcenters', '0002_capacityadjustment_workcenterloadsnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkcenterCapacityDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('workcenter_type', models.CharField(max_length=32)),
                ('capacity_unit', models.CharField(choices=[('PIECES_PER_DAY', 'Pieces per day'), ('SMV_MINUTES', 'SMV minutes'), ('BATCH_MINUTES', 'Batch minutes'), ('MACHINE_HOURS', 'Machine hours'), ('OPERATOR_HOURS', 'Operator hours'), ('LINE_DAYS', 'Line days'), ('CARTONS_PER_DAY', 'Cartons per day')], max_length=32)),
                ('planning_bucket', models.CharField(choices=[('SHIFT', 'Shift'), ('DAY', 'Day'), ('WEEK', 'Week'), ('BATCH', 'Batch')], max_length=16)),
                ('primary_constraint_resource', models.CharField(choices=[('MANPOWER', 'Manpower'), ('LINE_BALANCE', 'Line balance'), ('MACHINE_TIME', 'Machine time'), ('WASHER_TIME', 'Washer time'), ('DRYER_TIME', 'Dryer time'), ('SKILLED_OPERATOR', 'Skilled operator'), ('QC_CAPACITY', 'QC capacity'), ('PACKING_MANPOWER', 'Packing manpower'), ('DOCUMENTATION', 'Documentation')], max_length=40)),
                ('secondary_constraint_resource', models.CharField(blank=True, max_length=40)),
                ('normal_capacity_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('normal_capacity_unit', models.CharField(max_length=32)),
                ('overtime_allowed', models.BooleanField(default=False)),
                ('approved_overtime_capacity_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('capacity_loss_triggers_json', models.JSONField(blank=True, default=list)),
                ('recovery_levers_json', models.JSONField(blank=True, default=list)),
                ('active_status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['workcenter_type', 'planning_bucket'],
                'constraints': [models.UniqueConstraint(fields=('workcenter_type', 'planning_bucket'), name='unique_workcenter_capacity_definition_bucket')],
            },
        ),
    ]
