# Generated by Django 5.2.14 on 2026-05-26 20:28

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('required_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('required_stage', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ORDERED', 'Ordered'), ('READY', 'Ready'), ('SHORT', 'Short'), ('DELAYED', 'Delayed'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('shortage_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
            ],
            options={
                'ordering': ['order__order_no', 'required_stage', 'material__code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialETAUpdate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('previous_eta', models.DateField(blank=True, null=True)),
                ('revised_eta', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_eta_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('po_no', models.CharField(max_length=120, unique=True)),
                ('ordered_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('acknowledged_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('revised_eta', models.DateField(blank=True, null=True)),
                ('actual_arrival_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('DELAYED', 'Delayed'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='master_data.material')),
            ],
            options={
                'ordering': ['expected_arrival_date', 'po_no'],
            },
        ),
    ]
