# Generated by Django 5.2.14 on 2026-05-26 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('materials_procurement', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpurchaseorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_purchase_orders', to='orders.productionorder'),
        ),
        migrations.AddField(
            model_name='materialpurchaseorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialpurchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='master_data.vendor'),
        ),
        migrations.AddField(
            model_name='materialetaupdate',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eta_updates', to='materials_procurement.materialpurchaseorder'),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_requirements', to='master_data.material'),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='orders.productionorder'),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequirement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='materialrequirement',
            constraint=models.UniqueConstraint(fields=('order', 'material', 'required_stage'), name='unique_material_requirement_stage'),
        ),
    ]
