# Generated by Django 5.2.14 on 2026-05-27 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderchangerequest'),
        ('organization', '0001_initial'),
        ('planning', '0002_plannedworkitem_color_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryCaseEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('event_no', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('ORDER_CANCELLED', 'Order cancelled'), ('ORDER_QTY_CHANGED', 'Order quantity changed'), ('DELIVERY_DATE_CHANGED', 'Delivery date changed'), ('SHIPMENT_PULL_IN', 'Shipment pull-in'), ('CAPACITY_LOSS', 'Capacity loss'), ('CAPACITY_ADDITION', 'Capacity addition'), ('MACHINE_BREAKDOWN', 'Machine breakdown'), ('ABSENTEEISM_SPIKE', 'Absenteeism spike'), ('QC_FAILURE', 'QC failure'), ('REWASH_REQUIRED', 'Rewash required'), ('REWASH_REPEAT_EXCEEDED', 'Rewash repeat exceeded'), ('FROZEN_PLAN_CHANGE_REQUESTED', 'Frozen plan change requested'), ('EXTERNAL_PLAN_CONFLICT', 'External plan conflict')], max_length=48)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IMPACT_PREVIEWED', 'Impact previewed'), ('ACTION_PROPOSED', 'Action proposed'), ('APPROVAL_REQUIRED', 'Approval required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('linked_wash_batch_id', models.UUIDField(blank=True, null=True)),
                ('event_stage', models.CharField(blank=True, max_length=80)),
                ('trigger_source', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('SHOPFLOOR', 'Shopfloor'), ('IMPORT', 'Import'), ('INTEGRATION', 'Integration'), ('FASTREACT_IMPORT', 'FastReact import'), ('EXCEL_IMPORT', 'Excel import')], default='USER', max_length=32)),
                ('old_value_json', models.JSONField(blank=True, default=dict)),
                ('new_value_json', models.JSONField(blank=True, default=dict)),
                ('affected_quantity', models.IntegerField(default=0)),
                ('affected_capacity_minutes', models.IntegerField(default=0)),
                ('affected_shipment_date', models.DateField(blank=True, null=True)),
                ('risk_before', models.CharField(choices=[('ON_TRACK', 'On track'), ('WATCH', 'Watch'), ('ACTION', 'Action required'), ('CRITICAL', 'Critical')], default='ON_TRACK', max_length=20)),
                ('risk_after', models.CharField(choices=[('ON_TRACK', 'On track'), ('WATCH', 'Watch'), ('ACTION', 'Action required'), ('CRITICAL', 'Critical')], default='WATCH', max_length=20)),
                ('recommended_action', models.TextField(blank=True)),
                ('approval_required', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_boundary_events', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_boundary_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boundary_events', to='organization.line')),
                ('linked_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boundary_events', to='orders.productionorder')),
                ('linked_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boundary_events', to='planning.planversion')),
                ('linked_work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boundary_events', to='planning.plannedworkitem')),
                ('linked_workcenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boundary_events', to='organization.workcenter')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_boundary_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'event_no'],
            },
        ),
        migrations.CreateModel(
            name='BoundaryImpactPreview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('preview_type', models.CharField(max_length=80)),
                ('affected_orders_json', models.JSONField(blank=True, default=list)),
                ('affected_workcenters_json', models.JSONField(blank=True, default=list)),
                ('affected_wip_json', models.JSONField(blank=True, default=list)),
                ('affected_shipments_json', models.JSONField(blank=True, default=list)),
                ('capacity_before_json', models.JSONField(blank=True, default=dict)),
                ('capacity_after_json', models.JSONField(blank=True, default=dict)),
                ('risk_before', models.CharField(choices=[('ON_TRACK', 'On track'), ('WATCH', 'Watch'), ('ACTION', 'Action required'), ('CRITICAL', 'Critical')], default='ON_TRACK', max_length=20)),
                ('risk_after', models.CharField(choices=[('ON_TRACK', 'On track'), ('WATCH', 'Watch'), ('ACTION', 'Action required'), ('CRITICAL', 'Critical')], default='WATCH', max_length=20)),
                ('recommended_actions_json', models.JSONField(blank=True, default=list)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('blocking_reasons_json', models.JSONField(blank=True, default=list)),
                ('approval_required', models.BooleanField(default=False)),
                ('boundary_case_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impact_previews', to='boundary_cases.boundarycaseevent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
