# Generated by Django 5.2.14 on 2026-05-26 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('timezone', models.CharField(default='Asia/Jakarta', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'factories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('department_type', models.CharField(choices=[('PLANNING', 'Planning'), ('PRODUCTION', 'Production'), ('QUALITY', 'Quality'), ('WASH', 'Wash'), ('WAREHOUSE', 'Warehouse'), ('SHIPMENT', 'Shipment'), ('TECHNICAL', 'Technical'), ('ADMIN', 'Admin')], max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organization.factory')),
            ],
            options={
                'ordering': ['factory__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('holiday_date', models.DateField()),
                ('name', models.CharField(max_length=160)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holidays', to='organization.factory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['factory__code', 'holiday_date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftCalendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('working_minutes', models.PositiveIntegerField(default=480)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_calendars', to='organization.factory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['factory__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Workcenter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('workcenter_type', models.CharField(choices=[('CUTTING', 'Cutting'), ('SEWING', 'Sewing'), ('WASH', 'Wash'), ('FINISHING', 'Finishing'), ('PACKING', 'Packing'), ('QUALITY', 'Quality')], max_length=32)),
                ('capacity_unit', models.CharField(default='MINUTES', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workcenters', to='organization.department')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workcenters', to='organization.factory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['factory__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('line_type', models.CharField(default='SEWING', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='organization.department')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='organization.factory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workcenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='organization.workcenter')),
            ],
            options={
                'ordering': ['factory__code', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('factory', 'code'), name='unique_department_code_factory'),
        ),
        migrations.AddConstraint(
            model_name='holidaycalendar',
            constraint=models.UniqueConstraint(fields=('factory', 'holiday_date'), name='unique_holiday_date_factory'),
        ),
        migrations.AddConstraint(
            model_name='shiftcalendar',
            constraint=models.UniqueConstraint(fields=('factory', 'name'), name='unique_shift_name_factory'),
        ),
        migrations.AddConstraint(
            model_name='workcenter',
            constraint=models.UniqueConstraint(fields=('factory', 'code'), name='unique_workcenter_code_factory'),
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.UniqueConstraint(fields=('factory', 'code'), name='unique_line_code_factory'),
        ),
    ]
