# Generated by Django 5.2.14 on 2026-05-26 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricQCInspection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('inspection_date', models.DateField()),
                ('four_point_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width_result', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gsm_result', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shrinkage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('skewing_result', models.CharField(blank=True, max_length=80)),
                ('bowing_result', models.CharField(blank=True, max_length=80)),
                ('stretch_recovery_result', models.CharField(blank=True, max_length=80)),
                ('colorfastness_result', models.CharField(blank=True, max_length=80)),
                ('crocking_result', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('HOLD', 'Hold'), ('WAIVED', 'Waived')], max_length=20)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('waiver_reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FabricQCParameterResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('measured_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('text_value', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('HOLD', 'Hold'), ('WAIVED', 'Waived')], default='PENDING', max_length=20)),
                ('tolerance_min', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('tolerance_max', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'ordering': ['inspection', 'parameter__code'],
            },
        ),
        migrations.CreateModel(
            name='FabricRoll',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('roll_no', models.CharField(max_length=120)),
                ('roll_length', models.DecimalField(decimal_places=3, max_digits=14)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gsm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shade', models.CharField(blank=True, max_length=120)),
                ('qc_status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('HOLD', 'Hold'), ('WAIVED', 'Waived')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['fabric_lot__lot_no', 'roll_no'],
            },
        ),
        migrations.CreateModel(
            name='FabricLot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('lot_no', models.CharField(max_length=120)),
                ('shade_lot', models.CharField(blank=True, max_length=120)),
                ('received_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('received_date', models.DateField()),
                ('status', models.CharField(default='RECEIVED', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order__order_no', 'lot_no'],
            },
        ),
    ]
