# Generated by Django 5.2.14 on 2026-05-26 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabric_qc', '0001_initial'),
        ('materials_procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabriclot',
            name='material_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_lots', to='materials_procurement.materialpurchaseorder'),
        ),
    ]
