# Generated by Django 5.2.14 on 2026-05-26 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabric_qc', '0002_initial'),
        ('master_data', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fabriclot',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabric_lots', to='orders.productionorder'),
        ),
        migrations.AddField(
            model_name='fabriclot',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricqcinspection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricqcinspection',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabric_qc_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricqcinspection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricqcinspection',
            name='waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_fabric_qc_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricqcparameterresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricqcparameterresult',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_results', to='fabric_qc.fabricqcinspection'),
        ),
        migrations.AddField(
            model_name='fabricqcparameterresult',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_results', to='master_data.fabricqcparameter'),
        ),
        migrations.AddField(
            model_name='fabricqcparameterresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricroll',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricroll',
            name='fabric_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='fabric_qc.fabriclot'),
        ),
        migrations.AddField(
            model_name='fabricroll',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricqcinspection',
            name='fabric_roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='fabric_qc.fabricroll'),
        ),
        migrations.AddConstraint(
            model_name='fabriclot',
            constraint=models.UniqueConstraint(fields=('order', 'lot_no'), name='unique_fabric_lot_order'),
        ),
        migrations.AddConstraint(
            model_name='fabricqcparameterresult',
            constraint=models.UniqueConstraint(fields=('inspection', 'parameter'), name='unique_fabric_qc_parameter_result'),
        ),
        migrations.AddConstraint(
            model_name='fabricroll',
            constraint=models.UniqueConstraint(fields=('fabric_lot', 'roll_no'), name='unique_fabric_roll_lot'),
        ),
    ]
