# Generated by Django 5.2.14 on 2026-05-26 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PCDReadiness',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('planned_pcd_date', models.DateField()),
                ('readiness_status', models.CharField(choices=[('IN_REVIEW', 'In review'), ('READY', 'Ready'), ('CONDITIONALLY_READY', 'Conditionally ready'), ('BLOCKED', 'Blocked'), ('ESCALATED', 'Escalated'), ('RELEASED', 'Released')], default='IN_REVIEW', max_length=32)),
                ('conditional_release', models.BooleanField(default=False)),
                ('conditional_release_reason', models.TextField(blank=True)),
                ('conditional_release_expiry', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('released_to_cutting_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pcd_readiness', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pcd_readiness', to='orders.productionorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['planned_pcd_date', 'order__order_no'],
            },
        ),
        migrations.CreateModel(
            name='ConditionalRelease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20)),
                ('open_item_codes', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField()),
                ('risk_note', models.TextField(blank=True)),
                ('expiry_date', models.DateField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_conditional_releases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_conditional_releases', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('pcd_readiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_releases', to='pcd_readiness.pcdreadiness')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PCDReadinessItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('item_code', models.CharField(max_length=120)),
                ('item_label', models.CharField(max_length=250)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('WAIVED', 'Waived'), ('NOT_APPLICABLE', 'Not applicable')], default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('waiver_reason', models.TextField(blank=True)),
                ('evidence_url', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcd_readiness_items', to=settings.AUTH_USER_MODEL)),
                ('pcd_readiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pcd_readiness.pcdreadiness')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pcd_readiness__order__order_no', 'item_code'],
                'constraints': [models.UniqueConstraint(fields=('pcd_readiness', 'item_code'), name='unique_pcd_readiness_item_code')],
            },
        ),
    ]
