# Generated by Django 5.2.14 on 2026-05-27 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderchangerequest'),
        ('organization', '0001_initial'),
        ('production_release', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('job_no', models.CharField(max_length=120, unique=True)),
                ('planned_quantity', models.PositiveIntegerField()),
                ('marker_no', models.CharField(blank=True, max_length=120)),
                ('color_code', models.CharField(blank=True, max_length=80)),
                ('shade_lot', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('RELEASED', 'Released'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('HANDED_OVER', 'Handed over'), ('CANCELLED', 'Cancelled')], default='RELEASED', max_length=24)),
                ('risk_status', models.CharField(choices=[('ON_TRACK', 'On track'), ('WATCH', 'Watch'), ('ACTION', 'Action required'), ('CRITICAL', 'Critical')], default='ON_TRACK', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_jobs', to='orders.productionorder')),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_job', to='production_release.productionrelease')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workcenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_jobs', to='organization.workcenter')),
            ],
            options={
                'ordering': ['-created_at', 'job_no'],
            },
        ),
        migrations.CreateModel(
            name='CutBundle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('bundle_no', models.CharField(max_length=120, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('color_code', models.CharField(blank=True, max_length=80)),
                ('shade_lot', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ISSUED_TO_SEWING', 'Issued to sewing')], default='CREATED', max_length=24)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('cutting_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to='cutting.cuttingjob')),
            ],
            options={
                'ordering': ['cutting_job__job_no', 'bundle_no'],
            },
        ),
        migrations.CreateModel(
            name='CuttingOutputEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('client_event_id', models.CharField(max_length=120, unique=True)),
                ('output_qty', models.PositiveIntegerField()),
                ('defect_qty', models.PositiveIntegerField(default=0)),
                ('rework_qty', models.PositiveIntegerField(default=0)),
                ('net_cut_qty', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField()),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('cutting_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_entries', to='cutting.cuttingjob')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutting_output_entries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-created_at'],
            },
        ),
    ]
