# Generated by Django 5.2.14 on 2026-05-27 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boundary_cases', '0001_initial'),
        ('cutting', '0001_initial'),
        ('orders', '0002_orderchangerequest'),
        ('organization', '0001_initial'),
        ('production_release', '0001_initial'),
        ('sewing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WipLot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('lot_no', models.CharField(max_length=120, unique=True)),
                ('stage', models.CharField(choices=[('CUTTING', 'Cutting'), ('CUT_PANEL', 'Cut panel'), ('SEWING_ACTIVE', 'Sewing active'), ('SEWN_WAITING_WASH', 'Sewn waiting wash')], max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('available_quantity', models.PositiveIntegerField()),
                ('held_quantity', models.PositiveIntegerField(default=0)),
                ('color_code', models.CharField(blank=True, max_length=80)),
                ('shade_lot', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HELD', 'Held'), ('CONSUMED', 'Consumed')], default='AVAILABLE', max_length=24)),
                ('risk_status', models.CharField(choices=[('ON_TRACK', 'On track'), ('WATCH', 'Watch'), ('ACTION', 'Action required'), ('CRITICAL', 'Critical')], default='ON_TRACK', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('cutting_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip_lots', to='cutting.cuttingjob')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip_lots', to='organization.line')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_lots', to='orders.productionorder')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip_lots', to='production_release.productionrelease')),
                ('sewing_loading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip_lots', to='sewing.sewinglineloading')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workcenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip_lots', to='organization.workcenter')),
            ],
            options={
                'ordering': ['order__order_no', 'stage', 'lot_no'],
            },
        ),
        migrations.CreateModel(
            name='WipHandover',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('handover_no', models.CharField(max_length=120, unique=True)),
                ('target_stage', models.CharField(choices=[('CUTTING', 'Cutting'), ('CUT_PANEL', 'Cut panel'), ('SEWING_ACTIVE', 'Sewing active'), ('SEWN_WAITING_WASH', 'Sewn waiting wash')], max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(default='CONFIRMED', max_length=24)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_handovers', to='orders.productionorder')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_wip_handovers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_wip_handovers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('source_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_handovers', to='wip_inventory.wiplot')),
            ],
            options={
                'ordering': ['-created_at', 'handover_no'],
            },
        ),
        migrations.CreateModel(
            name='WipMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('movement_no', models.CharField(max_length=120, unique=True)),
                ('from_stage', models.CharField(blank=True, choices=[('CUTTING', 'Cutting'), ('CUT_PANEL', 'Cut panel'), ('SEWING_ACTIVE', 'Sewing active'), ('SEWN_WAITING_WASH', 'Sewn waiting wash')], max_length=32)),
                ('to_stage', models.CharField(choices=[('CUTTING', 'Cutting'), ('CUT_PANEL', 'Cut panel'), ('SEWING_ACTIVE', 'Sewing active'), ('SEWN_WAITING_WASH', 'Sewn waiting wash')], max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('movement_type', models.CharField(choices=[('RELEASE_TO_CUTTING', 'Release to cutting'), ('CUTTING_OUTPUT', 'Cutting output'), ('HANDOVER_TO_SEWING', 'Handover to sewing'), ('SEWING_OUTPUT', 'Sewing output'), ('CORRECTION', 'Correction')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('boundary_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip_movements', to='boundary_cases.boundarycaseevent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_movements', to='orders.productionorder')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip_movements', to=settings.AUTH_USER_MODEL)),
                ('source_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_movements', to='wip_inventory.wiplot')),
                ('target_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_movements', to='wip_inventory.wiplot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'movement_no'],
            },
        ),
        migrations.AddIndex(
            model_name='wiplot',
            index=models.Index(fields=['order', 'stage', 'status'], name='wip_invento_order_i_7a952e_idx'),
        ),
    ]
