# Generated by Django 5.2.14 on 2026-05-27 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('organization', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRelease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('release_no', models.CharField(max_length=100, unique=True)),
                ('release_date', models.DateField()),
                ('release_type', models.CharField(choices=[('CUTTING', 'Cutting'), ('SEWING', 'Sewing'), ('WASH', 'Wash'), ('FINISHING', 'Finishing')], default='CUTTING', max_length=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('BLOCKED', 'Blocked'), ('OVERRIDE_REQUESTED', 'Override requested'), ('OVERRIDE_APPROVED', 'Override approved'), ('RELEASED', 'Released'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=32)),
                ('risk_status', models.CharField(choices=[('ON_TRACK', 'On track'), ('WATCH', 'Watch'), ('ACTION', 'Action required'), ('CRITICAL', 'Critical')], default='ON_TRACK', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_releases', to='orders.productionorder')),
                ('override_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_release_overrides', to=settings.AUTH_USER_MODEL)),
                ('override_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_release_overrides', to=settings.AUTH_USER_MODEL)),
                ('planned_work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_releases', to='planning.plannedworkitem')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_production_releases', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workcenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_releases', to='organization.workcenter')),
            ],
            options={
                'ordering': ['release_date', 'release_no'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseValidationResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('risk_status', models.CharField(choices=[('ON_TRACK', 'On track'), ('WATCH', 'Watch'), ('ACTION', 'Action required'), ('CRITICAL', 'Critical')], default='ON_TRACK', max_length=20)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_validation_results', to='orders.productionorder')),
                ('planned_work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_validation_results', to='planning.plannedworkitem')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='production_release.productionrelease')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseBlocker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('blocker_code', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('WATCH', 'Watch'), ('ACTION', 'Action'), ('CRITICAL', 'Critical')], default='ACTION', max_length=20)),
                ('owner_role', models.CharField(blank=True, max_length=80)),
                ('resolved', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='production_release.productionrelease')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('validation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker_rows', to='production_release.releasevalidationresult')),
            ],
            options={
                'ordering': ['resolved', 'severity', 'blocker_code'],
            },
        ),
    ]
