# Generated by Django 5.2.14 on 2026-05-27 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedworkitem',
            name='color_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='plannedworkitem',
            name='planned_shift',
            field=models.CharField(default='DAY', max_length=40),
        ),
        migrations.AddField(
            model_name='plannedworkitem',
            name='planning_zone',
            field=models.CharField(choices=[('FROZEN_ZONE', 'Frozen zone'), ('FIRM_ZONE', 'Firm zone'), ('FLEXIBLE_ZONE', 'Flexible zone')], default='FLEXIBLE_ZONE', max_length=32),
        ),
        migrations.AddField(
            model_name='plannedworkitem',
            name='production_stage',
            field=models.CharField(default='PLANNING', max_length=40),
        ),
        migrations.AddField(
            model_name='plannedworkitem',
            name='shade_lot',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='planchangerequest',
            name='change_type',
            field=models.CharField(choices=[('ASSIGN', 'Assign'), ('MOVE', 'Move'), ('CAPACITY', 'Capacity'), ('RELEASE', 'Release'), ('BOUNDARY_REPLAN', 'Boundary replan')], default='MOVE', max_length=24),
        ),
        migrations.CreateModel(
            name='PlanningZoneConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('zone_code', models.CharField(choices=[('FROZEN_ZONE', 'Frozen zone'), ('FIRM_ZONE', 'Firm zone'), ('FLEXIBLE_ZONE', 'Flexible zone')], max_length=32, unique=True)),
                ('zone_name', models.CharField(max_length=120)),
                ('horizon_start_days', models.PositiveIntegerField(default=0)),
                ('horizon_end_days', models.PositiveIntegerField(default=0)),
                ('requires_approval_for_change', models.BooleanField(default=False)),
                ('auto_reschedule_allowed', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['horizon_start_days', 'zone_code'],
            },
        ),
    ]
