# Generated by Django 5.2.14 on 2026-05-27 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0002_plannedworkitem_color_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPlanImportBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('import_no', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('fastreact_plan', 'FastReact plan'), ('external_plan', 'External plan')], default='external_plan', max_length=40)),
                ('status', models.CharField(choices=[('IMPORTED', 'Imported'), ('VALIDATED', 'Validated'), ('DRAFT_CREATED', 'Draft created'), ('REJECTED', 'Rejected')], default='IMPORTED', max_length=32)),
                ('source_reference', models.CharField(blank=True, max_length=160)),
                ('raw_rows_json', models.JSONField(blank=True, default=list)),
                ('validation_summary_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('created_draft_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_plan_imports', to='planning.planversion')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_plan_imports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'import_no'],
            },
        ),
        migrations.CreateModel(
            name='ExternalPlanValidationResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('conflict_type', models.CharField(choices=[('ORDER_NOT_FOUND', 'Order not found'), ('STYLE_NOT_READY', 'Style not ready'), ('LINE_NOT_FOUND', 'Line not found'), ('WORKCENTER_NOT_FOUND', 'Workcenter not found'), ('CAPACITY_OVERLOAD', 'Capacity overload'), ('PCD_NOT_READY', 'PCD not ready'), ('WIP_NOT_AVAILABLE', 'WIP not available'), ('WASH_ROUTE_MISSING', 'Wash route missing'), ('SHIPMENT_RISK', 'Shipment risk'), ('FROZEN_ZONE_CONFLICT', 'Frozen zone conflict')], max_length=40)),
                ('severity', models.CharField(default='ACTION', max_length=16)),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('order_no', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='external_plans.externalplanimportbatch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['row_number', 'conflict_type'],
            },
        ),
    ]
